name: Build Plugin on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Cmajor
        uses: actions/checkout@v2
        with:
          repository: cmajor-lang/cmajor
          path: cmajor
          fetch-depth: 1

      - name: Cache Cmajor Build
        id: cmajor-cache
        uses: actions/cache@v3
        with:
          path: cmajor/build
          key: cmajor-build-${{ hashFiles('cmajor/**/CMakeLists.txt') }}-4

      - name: Convert submodule URLs from SSH to HTTPS
        if: steps.cmajor-cache.outputs.cache-hit != 'true'
        run: |
          cd cmajor
          git submodule deinit -f .
          git config --global url."https://github.com/".insteadOf git@github.com:
          git submodule update --init --recursive --depth 1

      - name: Build Cmajor if cache misses
        if: steps.cmajor-cache.outputs.cache-hit != 'true'
        run: |
          cd cmajor
          cmake -Bbuild -G "Visual Studio 17 2022" -A x64 .
          cmake --build build --config Release

      - name: Checkout CLAP
        uses: actions/checkout@v2
        with:
          repository: clap-rs/clap
          path: clap
          fetch-depth: 1

      - name: Generate CLAP Plugin
        run: ./cmajor/build/tools/command/Release/cmaj.exe generate --target=clap --output=./oscilluna-clap --clapIncludePath=./clap/include --cmajorIncludePath=./cmajor/include Oscilluna.cmajorpatch

      # - name: Upload Cmajor Build Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: cmajor-build
      #     path: ./build
