name: Build Plugin on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cache-cmajor:
    runs-on: windows-latest

    steps:
      - name: Checkout Cmajor
        uses: actions/checkout@v2
        with:
          repository: cmajor-lang/cmajor
          fetch-depth: 1

      - name: Convert submodule URLs from SSH to HTTPS
        run: |
          git submodule deinit -f .
          git config --global url."https://github.com/".insteadOf git@github.com:
          git submodule update --init --recursive --depth 1

      - name: Cache Cmajor Build
        uses: actions/cache@v3
        with:
          path: ./build/cmajor
          key: cmajor-build-${{ hashFiles('**/CMakeLists.txt') }}-2

      - name: Build Cmajor if cache misses
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cmake -Bbuild -G "Visual Studio 17 2022" -A x64 .
          cmake --build build --config Release

      - name: Upload Cmajor Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cmajor-build
          path: ./build
