name: Build Plugin on Windows

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Cmajor
        uses: actions/checkout@v2
        with:
          repository: cmajor-lang/cmajor
          path: cmajor
          fetch-depth: 1

      - name: Cache Cmajor Build
        id: cmajor-cache
        uses: actions/cache@v3
        with:
          path: cmajor/build
          key: cmajor-build-${{ hashFiles('cmajor/**/CMakeLists.txt') }}-4

      - name: Convert submodule URLs from SSH to HTTPS
        if: steps.cmajor-cache.outputs.cache-hit != 'true'
        run: |
          cd cmajor
          git submodule deinit -f .
          git config --global url."https://github.com/".insteadOf git@github.com:
          git submodule update --init --recursive --depth 1

      - name: Build Cmajor if cache misses
        if: steps.cmajor-cache.outputs.cache-hit != 'true'
        run: |
          cd cmajor
          cmake -Bbuild -G "Visual Studio 17 2022" -A x64 .
          cmake --build build --config Release

      - name: Initialize choc
        run: |
          cd cmajor
          git config --global url."https://github.com/".insteadOf git@github.com:
          git submodule update --init --recursive --depth 1 -- include/choc

      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          path: src

      - name: Checkout CLAP
        uses: actions/checkout@v2
        with:
          repository: free-audio/clap
          path: clap
          fetch-depth: 1

      - name: Generate CLAP Plugin
        run: ./cmajor/build/tools/command/Release/cmaj.exe generate --target=clap --output=${{ github.workspace }}\\oscilluna-clap --clapIncludePath=${{ github.workspace }}\\clap\\include --cmajorIncludePath=${{ github.workspace }}\\cmajor\\include ${{ github.workspace }}\\src\\Oscilluna.cmajorpatch

      - name: Build CLAP plugin
        run: |
          cd oscilluna-clap
          cmake -B build -DCLAP_INCLUDE_PATH="${{ github.workspace }}\\clap\\include" -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: oscilluna-clap/build/Release/Oscilluna.clap
          tag_name: ${{ github.ref_name }}
          name: Oscilluna CLAP Plugin (Windows) - ${{ github.ref_name }}"
          prerelease: false
